# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet test -c Release tests/Avalonia.Controls.TreeDataGrid.Tests
  displayName: 'Run Unit Tests'

- script: dotnet pack -c Release src/Avalonia.Controls.TreeDataGrid
  displayName: 'Generate Nuget Package'
